#!/usr/bin/env python

from datetime import datetime
from dateutil import parser

from hikvisionapi import Client

cam = Client('http://10.100.151.185', 'admin', 'cVis_100', timeout=30)

while 1:
    alerts = cam.Event.notification.alertStream(method='get', type='Stream') #судя по всему здесь считывается список оповещений
    #с камеры, которая передает поток видео с камер

    for alert in alerts: #проверяем каждое оповещение из последовательности оповещений
        alert_details = alert.get('EventNotificationAlert', None) #возвращаем детали оповещения
        if alert_details is None: #если деталей оповещения нет
            continue

        if alert_details['eventType'] != 'PeopleCounting': #если тип события это не подсчет людей
            continue

        stat_method = alert_details.get('statisticalMethods', None) #чепроисходит
        if stat_method is None:
            continue

        time_begin = time_end = datetime.now() #???

        if stat_method == 'realTime':
            realTime = alert_details['RealTime']
            time_begin = time_end = parser.parse(realTime['time'])
        elif stat_method == 'timeRange':
            timeRange = alert_details['TimeRange']
            time_begin = parser.parse(timeRange['startTime'])
            time_end = parser.parse(timeRange['endTime'])
        else:
            continue

        print(stat_method, time_begin, time_end, alert_details)
